import {mkdir, readFile, writeFile, copyFile, cp, rm} from 'node:fs/promises';
import {build} from 'esbuild';
const url=process.env.PUBLIC_SUPABASE_URL;
const key=process.env.PUBLIC_SUPABASE_PUBLISHABLE_KEY;
if(!url || !key) throw new Error('Set PUBLIC_SUPABASE_URL and PUBLIC_SUPABASE_PUBLISHABLE_KEY in Vercel before deploying.');
if(!/^https:\/\/[a-z0-9]+\.supabase\.co$/.test(url)) throw new Error('Expected the Supabase project HTTPS URL.');
if(!key.startsWith('sb_publishable_')) throw new Error('Use a publishable key, never a secret or service-role key.');
await rm('dist',{recursive:true,force:true});
await mkdir('dist',{recursive:true});
for(const name of ['app.js','style.css','theme.js','brand-wave.js']) await copyFile(`web/${name}`,`dist/${name}`);
await cp('web/icons','dist/icons',{recursive:true});
await cp('web/fonts','dist/fonts',{recursive:true});
let html=await readFile('web/index.html','utf8');
html=html.replace('content="__LOCAL_TOKEN__"','content=""').replace('<script type="module" src="/app.js"></script>','<script type="module" src="/cloud.js"></script>');
html=html.replace('<main>','<main hidden>');
const policy="default-src 'self'; script-src 'self'; style-src 'self'; font-src 'self'; connect-src 'self' "+url+"; img-src 'self' blob: data: https://pbs.twimg.com; media-src https://video.twimg.com; object-src 'none'; base-uri 'none'; form-action 'self'";
html=html.replace('<head>','<head><meta http-equiv="Content-Security-Policy" content="'+policy+'">');
await writeFile('dist/index.html',html);
await build({entryPoints:['cloud/client.js'],bundle:true,external:['/app.js'],format:'esm',outfile:'dist/cloud.js',minify:true,define:{SUPABASE_URL:JSON.stringify(url),SUPABASE_KEY:JSON.stringify(key)}});
console.log('Built private cloud library. Local server, pairing keys and capture data are not deployed.');
