const $ = s => document.querySelector(s);
const token = $('meta[name="local-token"]').content;
let state=null, section='x_post', query='', activeId=null, detailIds=[], returnFocus=null, pendingRefresh=false;
const gridCleanups=[],detailCleanups=[],players=new Set(), imageCache=new Map();
const dialog=$('#detail');
async function api(path,method='GET',data){const r=window.libraryAPI?await window.libraryAPI.request(path,method,data):await fetch(path,{method,headers:{'X-Capture-Token':token,...(data?{'Content-Type':'application/json'}:{})},body:data?JSON.stringify(data):undefined});if(!r.ok){let e;try{e=await r.json();}catch{}throw Error(e?.error||'Could not reach your library.');}return r;}
function el(tag,text,cls){const n=document.createElement(tag);if(text)n.textContent=text;if(cls)n.className=cls;return n;}
function icon(name){const i=el('img');i.src=`/icons/${name}.svg`;i.alt='';return i;}
function btn(name,action,cls=''){const b=el('button',name,cls);b.type='button';b.addEventListener('click',e=>{e.stopPropagation();Promise.resolve(action(e)).catch(error);});return b;}
function iconButton(name,label,action,cls=''){const b=btn('',action,`icon-button ${cls}`);b.append(icon(name));b.setAttribute('aria-label',label);b.title=label;return b;}
function sourceLink(item,cls,label){const a=el('a',null,cls);a.href=item.url;a.target='_blank';a.rel='noopener noreferrer';a.setAttribute('aria-label',label);a.title=label;a.append(icon('arrow-up-right'));a.addEventListener('click',e=>e.stopPropagation());return a;}
function error(e){$('#status').textContent=e.message;if(dialog.open){let n=$('#detail-error');if(!n){n=el('p',null,'motion-note');n.id='detail-error';n.setAttribute('role','alert');$('#detail-copy').append(n);}n.textContent=e.message;}}
function metadata(item){return state.x_metadata?.[item.post_id]||{};}
function author(item){const m=metadata(item), observed=item.author_observed||'';return {name:m.author_name||observed.replace(/\s*@\w+\s*$/,'').trim()||'Author unavailable',handle:m.author_handle||observed.match(/@(\w+)\s*$/)?.[1]||'',avatar:m.avatar};}
function avatar(item){const a=author(item),img=el('img',null,'avatar');img.alt=a.name;if(a.avatar){img.src=a.avatar;img.addEventListener('error',()=>{img.src='/icons/user.svg';img.classList.add('fallback');},{once:true});}else{img.src='/icons/user.svg';img.classList.add('fallback');}return img;}
function postText(item){return metadata(item).text||item.description||item.title;}
function shortTitle(item){const text=postText(item).replace(/https?:\/\/\S+/g,'').trim();const first=text.split(/\n|(?<=[.!?])\s/)[0]||item.title;return first.length>92?first.slice(0,89).trimEnd()+'…':first;}
function date(value){if(!value)return '';const d=new Date(value);return Number.isNaN(+d)?'':d.toLocaleDateString(undefined,{day:'numeric',month:'short',year:'numeric'});}
async function imageURL(item){const key=`${item.id}:${item.updated_at}`;if(!imageCache.has(key)){imageCache.set(key,api(`/api/image/${item.id}`).then(r=>r.blob()).then(b=>URL.createObjectURL(b)).catch(e=>{imageCache.delete(key);throw e;}));}return imageCache.get(key);}
function motionPreview(item,media,scope,mediaPoster){const wrap=el('div',null,'motion-wrap'),video=el('video',null,'motion-video');video.muted=true;video.defaultMuted=true;video.loop=true;video.playsInline=true;video.preload='none';video.width=media.width;video.height=media.height;video.setAttribute('aria-label',`Video by ${author(item).name}`);const controls=el('div',null,'motion-controls'),note=el('p',null,'motion-note');note.setAttribute('role','status');let visible=false,disposed=false,blocked=false;const reduced=matchMedia('(prefers-reduced-motion: reduce)');
async function sync(){if(disposed)return;if(!visible||document.hidden||(dialog.open&&scope==='grid')||reduced.matches){video.pause();return;}if(blocked)return;if(!video.src)video.src=media.url;try{await video.play();if(!disposed)note.textContent='';}catch(e){if(disposed||e.name==='AbortError')return;blocked=true;note.classList.remove('reduced-note');note.textContent=e.name==='NotAllowedError'?'Autoplay unavailable. Open the original post to watch.':'Preview unavailable. You can still open the original post.';controls.classList.add('needs-action');}}
const sound=iconButton('speaker-slash','Unmute preview',()=>{video.muted=!video.muted;sound.replaceChildren(icon(video.muted?'speaker-slash':'speaker-high'));sound.setAttribute('aria-label',video.muted?'Unmute preview':'Mute preview');sound.title=video.muted?'Unmute preview':'Mute preview';});if(scope==='detail')controls.append(sound);wrap.append(video,controls,note);video.addEventListener('error',()=>{blocked=true;note.classList.remove('reduced-note');note.textContent='Preview unavailable. You can still open the original post.';controls.classList.add('needs-action');});
const poster=mediaPoster===undefined?state.x_images?.[item.post_id]:mediaPoster;if(poster)video.poster=poster;else if(item.has_preview)imageURL(item).then(u=>{if(!disposed)video.poster=u;}).catch(()=>{});
const io=new IntersectionObserver(entries=>{visible=entries[0].isIntersecting&&entries[0].intersectionRatio>=(scope==='detail'?.6:.1);sync();},{threshold:scope==='detail'?.6:.1});io.observe(wrap);const preference=()=>{note.classList.toggle('reduced-note',reduced.matches);note.textContent=reduced.matches?'Reduced motion: preview paused. Open the original post to watch.':'';controls.classList.toggle('needs-action',reduced.matches);sync();};if(reduced.matches){note.classList.add('reduced-note');note.textContent='Reduced motion: preview paused. Open the original post to watch.';controls.classList.add('needs-action');}reduced.addEventListener('change',preference);document.addEventListener('visibilitychange',sync);const player={sync,video};players.add(player);(scope==='detail'?detailCleanups:gridCleanups).push(()=>{disposed=true;io.disconnect();video.pause();video.removeAttribute('src');video.load();players.delete(player);reduced.removeEventListener('change',preference);document.removeEventListener('visibilitychange',sync);});return wrap;}
function mediaPreview(item,scope){const motion=state.motion?.[item.post_id];if(motion)return motionPreview(item,motion,scope);const remote=state.x_images?.[item.post_id];if(remote||item.has_preview){const img=el('img',null,'media media-image');img.alt=`Preview of ${item.kind==='x_post'?shortTitle(item):item.title}`;img.loading=scope==='detail'?'eager':'lazy';if(remote)img.src=remote;else imageURL(item).then(u=>{img.src=u;}).catch(()=>{img.replaceWith(el('div','Preview unavailable. Open the source to view this reference.','text-preview'));});img.addEventListener('error',()=>img.replaceWith(el('div','Preview unavailable. Open the source to view this reference.','text-preview')),{once:true});return img;}return el('div',postText(item)||'Open the source to view this reference.','text-preview');}
// Keep the first attachment as the grid cover; expanded albums retain source order.
function albumItems(item){return metadata(item).media||[];}
function albumPreview(item){
 const attachments=albumItems(item),gallery=el('section',null,'album-gallery'),track=el('div',null,'album-track'),controls=el('div',null,'album-controls');
 gallery.setAttribute('aria-label','Post media gallery');track.tabIndex=0;track.setAttribute('aria-label','Images and videos. Use left and right arrows to browse.');
 const ratio=m=>m.width>0&&m.height>0?m.width/m.height:1;gallery.style.setProperty('--first-ratio',ratio(attachments[0]));gallery.style.setProperty('--last-ratio',ratio(attachments.at(-1)));
 let current=0;const slides=[];
 const counter=el('span',null,'album-counter');counter.setAttribute('role','status');counter.setAttribute('aria-live','polite');
 const previous=iconButton('arrow-left','Previous image',()=>go(current-1));
 const next=iconButton('arrow-right','Next image',()=>go(current+1));
 function update(){counter.textContent=`${current+1} / ${attachments.length}`;previous.disabled=current===0;next.disabled=current===attachments.length-1;}
 function go(index){const target=slides[Math.max(0,Math.min(slides.length-1,index))];track.scrollTo({left:target.offsetLeft-(track.clientWidth-target.offsetWidth)/2,behavior:'instant'});}
 for(const [index,media] of attachments.entries()){
  const slide=el('div',null,'album-slide');slide.style.setProperty('--media-ratio',ratio(media));slide.setAttribute('role','group');slide.setAttribute('aria-label',`Media ${index+1} of ${attachments.length}`);
  if(media.motion)slide.append(motionPreview(item,media.motion,'detail',media.poster));
  else if(media.poster){const img=el('img',null,'media media-image');img.src=media.poster;img.alt=media.alt||`Image ${index+1} of ${attachments.length} — ${shortTitle(item)}`;img.loading=index===0?'eager':'lazy';if(media.width&&media.height){img.width=media.width;img.height=media.height;}img.addEventListener('error',()=>img.replaceWith(el('p','Image unavailable. Open the original post.','text-preview')),{once:true});slide.append(img);}
  else slide.append(el('p','Media unavailable. Open the original post.','text-preview'));
  slides.push(slide);track.append(slide);
 }
 track.addEventListener('scroll',()=>{const center=track.scrollLeft+track.clientWidth/2;current=slides.reduce((best,slide,i)=>Math.abs(slide.offsetLeft+slide.offsetWidth/2-center)<Math.abs(slides[best].offsetLeft+slides[best].offsetWidth/2-center)?i:best,0);update();},{passive:true});
 track.addEventListener('keydown',e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();e.stopPropagation();go(current+(e.key==='ArrowRight'?1:-1));}});
 controls.append(previous,counter,next);gallery.append(track,controls);update();return gallery;
}
const resizeObserver=new ResizeObserver(entries=>{for(const {target} of entries){const card=target.parentElement;if(card?.parentElement?.classList.contains('masonry'))card.style.gridRowEnd=`span ${Math.ceil(target.getBoundingClientRect().height+20)}`;}});
function filteredItems(){return state.captures.filter(i=>!i.fixture&&i.kind===section&&(!query||[i.title,i.description,author(i).name,author(i).handle,i.url].join(' ').toLowerCase().includes(query)));}
function renderGrid(){if(!state)return;for(const c of gridCleanups.splice(0))c();resizeObserver.disconnect();const grid=$('#captures');grid.replaceChildren();grid.className=section==='x_post'?'masonry':'web-grid';const items=filteredItems();
if(!items.length){grid.className='web-grid';const empty=el('div',null,'empty');empty.append(el('h2',query?'No matching references':'Your collection starts here'),el('p',query?'Try another search.':section==='x_post'?(window.libraryAPI?.cloud?'Import your local collection to bring your saved references here.':'New bookmarks on X will appear after the next sync.'):'Save a website with the browser extension.'));grid.append(empty);return;}
for(const item of items){const card=el('article',null,section==='x_post'?'card':'website-card');card.dataset.id=item.id;if(section==='x_post'){const surface=el('div',null,'card-surface');surface.append(mediaPreview(item,'grid'));const open=btn('',()=>openDetail(item.id,open),'open-card');open.setAttribute('aria-label',`Open reference: ${shortTitle(item)}`);surface.append(open);const count=albumItems(item).length;if(count>1){const badge=el('span',String(count),'album-count');badge.setAttribute('aria-label',`${count} media items`);surface.append(badge);}card.append(surface);grid.append(card);resizeObserver.observe(surface);}else{const image=el('a',null,'website-image');image.href=item.url;image.target='_blank';image.rel='noopener noreferrer';image.setAttribute('aria-label',`Visit ${item.title}`);image.append(mediaPreview(item,'grid'));const title=el('h2'),titleLink=el('a',item.title);titleLink.href=item.url;titleLink.target='_blank';titleLink.rel='noopener noreferrer';titleLink.title=item.title;title.append(titleLink);const url=el('a',new URL(item.url).hostname.replace(/^www\./,''),'website-url');url.href=item.url;url.target='_blank';url.rel='noopener noreferrer';card.append(image,title,url);if(window.libraryAPI?.cloud)card.append(btn('Move to Trash',async()=>{await api('/api/trash','POST',{id:item.id});await refresh();},'text-action'));grid.append(card);}}
}
function syncSummary(){if(window.libraryAPI?.cloud){const b=state?.bookmarks;$('#sync-status').textContent=state?.cloud_error?'Cloud status unavailable':b?.enabled?`Cloud saves · Next X check ${new Date(b.next_check*1000).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}`:'Cloud saves · X checks paused';$('#sync-status').title=b?.message||'';return;}const c=state?.cloud_sync;const cloudLabel=document.querySelector('#cloud-status');if(cloudLabel)cloudLabel.textContent=c?.needs_sign_in?'Cloud · Sign in again':c?.enabled?(c.pending?`Cloud · ${c.pending} waiting`:'Cloud · Saved'):'Cloud · Connect or resume';const b=state?.bookmarks;if(!b){$('#sync-status').textContent='Saved locally';return;}$('#sync-status').textContent=b.enabled?'X sync on · Checks every 15 minutes':b.phase==='ready'?'X sync paused · Manage in Capture Lab':'Connect X in Capture Lab';$('#sync-status').title=b.message||'';}
async function refresh(){const next=await(await api('/api/state')).json();if(dialog.open){state.bookmarks=next.bookmarks;state.cloud_sync=next.cloud_sync;syncSummary();pendingRefresh=true;return;}state=next;$('#count-x').textContent=state.captures.filter(i=>!i.fixture&&i.kind==='x_post').length;$('#count-web').textContent=state.captures.filter(i=>!i.fixture&&i.kind==='website').length;syncSummary();renderGrid();}
function renderDetail(){for(const c of detailCleanups.splice(0))c();const item=state.captures.find(i=>i.id===activeId);if(!item){dialog.close();return;}const copy=$('#detail-copy');copy.replaceChildren();const head=el('div',null,'detail-heading'),title=el('h2',shortTitle(item));title.id='detail-title';head.append(title);const a=author(item),authorLine=el('div',null,'author-line'),name=el('div',a.name);if(a.handle)name.append(el('small','@'+a.handle));authorLine.append(avatar(item),name);copy.append(head,authorLine);let fullText=postText(item).replace(/https?:\/\/t\.co\/\S+/g,'').trim();const heading=shortTitle(item);if(fullText.startsWith(heading))fullText=fullText.slice(heading.length).trim();if(fullText)copy.append(el('p',fullText,'post-text'));const dates=el('div',null,'detail-dates');dates.append(el('p',`Added ${date(item.created_at)}`));if(metadata(item).published_at)dates.append(el('p',`Posted ${date(metadata(item).published_at)}`));const source=sourceLink(item,'source-link','Open original X post');source.prepend(document.createTextNode('View on X'));copy.append(dates,source);if(window.libraryAPI?.cloud){copy.append(btn('Move to Trash',async()=>{await api('/api/trash','POST',{id:item.id});dialog.close();await refresh();},'text-action'),btn('Refresh preview from X',async()=>{const result=await(await api('/api/refresh-media','POST',{id:item.id})).json();error({message:result.message});pendingRefresh=true;},'text-action'));}const media=el('div',null,'detail-media');const album=albumItems(item).length>1;$('#detail-stage').classList.toggle('has-album',album);media.append(album?albumPreview(item):mediaPreview(item,'detail'));$('#detail-stage').replaceChildren(media);const index=detailIds.indexOf(activeId);$('#previous-detail').disabled=index<=0;$('#next-detail').disabled=index>=detailIds.length-1;}
function openDetail(id,trigger){activeId=id;detailIds=filteredItems().map(i=>i.id);returnFocus=trigger;dialog.showModal();document.body.classList.add('detail-open');for(const p of players)p.sync();renderDetail();$('#close-detail').focus();}
function navigateDetail(offset){const index=detailIds.indexOf(activeId),next=detailIds[index+offset];if(next){activeId=next;renderDetail();}}
$('#close-detail').addEventListener('click',()=>dialog.close());$('#previous-detail').addEventListener('click',()=>navigateDetail(-1));$('#next-detail').addEventListener('click',()=>navigateDetail(1));dialog.addEventListener('click',e=>{if(e.target===$('#detail-stage'))dialog.close();});dialog.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName))return;if(e.key==='ArrowLeft'){e.preventDefault();navigateDetail(-1);}if(e.key==='ArrowRight'){e.preventDefault();navigateDetail(1);}});dialog.addEventListener('close',()=>{for(const c of detailCleanups.splice(0))c();$('#detail-stage').replaceChildren();document.body.classList.remove('detail-open');activeId=null;for(const p of players)p.sync();returnFocus?.focus();if(pendingRefresh){pendingRefresh=false;refresh().then(()=>{const id=returnFocus?.closest('[data-id]')?.dataset.id;document.querySelector(`[data-id="${id}"] .open-card`)?.focus();}).catch(error);}});
function switchSection(kind){section=kind;query='';$('#search').value='';$('#tab-x').classList.toggle('active',kind==='x_post');$('#tab-web').classList.toggle('active',kind==='website');$('#tab-x').setAttribute('aria-pressed',String(kind==='x_post'));$('#tab-web').setAttribute('aria-pressed',String(kind==='website'));renderGrid();}
$('#tab-x').addEventListener('click',()=>switchSection('x_post'));$('#tab-web').addEventListener('click',()=>switchSection('website'));let searchTimer;$('#search').addEventListener('input',e=>{query=e.target.value.trim().toLowerCase();clearTimeout(searchTimer);searchTimer=setTimeout(renderGrid,160);});
if(!window.libraryAPI?.cloud){const link=el('a','Cloud saves');link.id='cloud-status';link.href='/cloud';document.querySelector('footer').append(link);}
window.addEventListener('library-refresh',()=>refresh().catch(error));
refresh().catch(error);
// Local reads only; browsing and searching never request paid X data.
setInterval(async()=>{if(document.hidden||!state)return;try{const next=await(await api('/api/state')).json();state.bookmarks=next.bookmarks;state.cloud_sync=next.cloud_sync;syncSummary();const signature=value=>JSON.stringify([value.captures.map(i=>[i.id,i.updated_at]),value.motion,value.x_images,value.x_metadata]);if(signature(next)!==signature(state)){if(dialog.open){pendingRefresh=true;return;}state=next;renderGrid();$('#count-x').textContent=next.captures.filter(i=>!i.fixture&&i.kind==='x_post').length;$('#count-web').textContent=next.captures.filter(i=>!i.fixture&&i.kind==='website').length;}}catch{$('#sync-status').textContent=window.libraryAPI?.cloud?'Could not refresh your library · Check your connection':'Local server unavailable · Your saved cards are still on this Mac';}},15000);
